import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import type { Metadata } from 'next'
import { Inter, Roboto_Serif } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/shared/navbar/NavBar'
import Footer from '@/components/shared/footer/Footer'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto_Serif({ subsets: ['latin'], variable: '--font-roboto' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable}`}>
        <Theme>
          <NavBar />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
