import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Serif, DM_Serif_Display } from "next/font/google";
import Footer from "@/components/shared/footer/Footer";
import CurrentUserProvider from "@/components/current-user/provider";
import { Toaster } from "react-hot-toast";
import { Header } from "@/components/shared/header";
import { cookies } from "next/headers";
import { getAllCategories } from "@/services/courses/multi-course";

const roboto = Roboto_Serif({ subsets: ["latin"], variable: "--font-roboto" });
const serifFont = DM_Serif_Display({
  subsets: ["latin"],
  variable: "--font-title",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let token: string | null = "";
  try {
    const nextCookies = cookies();
    token = nextCookies.get("token")?.value ?? null;
    if (!token) throw "not logged in";
  } catch (error) {}
  const categories = await getAllCategories(token);

  return (
    <html lang="en">
      <body className={`${roboto.variable} ${serifFont.variable}`}>
        <Toaster position="bottom-right" />
        <CurrentUserProvider>
          <main className="flex min-h-svh flex-col">
            <Header categories={categories} />
            {children}
            <Footer categories={categories} />
          </main>
        </CurrentUserProvider>
      </body>
    </html>
  );
}
