import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";
import NavBar from "@/components/shared/navbar/NavBar";
import Footer from "@/components/shared/footer/Footer";
import CurrentUserProvider from "@/components/current-user/provider";

const roboto = Roboto_Serif({ subsets: ["latin"], variable: "--font-roboto" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <CurrentUserProvider>
          <Theme>
            <NavBar />
            <main className="px-2">
              {children}
              <Footer />
            </main>
          </Theme>
        </CurrentUserProvider>
      </body>
    </html>
  );
}
